site_name: Agentic Onto Triplecast
site_url: https://growgraph.github.io/ontocast
repo_url: https://github.com/growgraph/ontocast
repo_name: growgraph/ontocast
copyright: Copyright &copy; 2025 GrowGraph

theme:
    name: material
    user_color_mode_toggle: true
    palette:
    -   scheme: default
        primary: orange
        accent: brown
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    -   scheme: slate
        primary: brown
        accent: lime
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    logo: assets/project_logo.png
    icon:
        repo: fontawesome/brands/github
    favicon: assets/favicon.ico

plugins:
-   search
-   glightbox
-   gen-files:
        scripts:
        -   docs/gen_pages.py
-   literate-nav
-   mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    extra:
                        show_root_full_path: true
                        show_docstring: true
                        show_source: true
                        show_root_toc_entry: false
                        docstring_style: google
                        show_submodules: true
                        show_category_heading: true
                        show_if_no_docstring: true
                        setup_commands:
                        -   "import sys"
                        -   "sys.path.append('.')"

nav:
-   Home: index.md
-   Getting Started:
    -   Installation: getting_started/installation.md
    -   Quick Start: getting_started/quickstart.md
    -   Configuration: getting_started/configuration.md
-   User Guide:
    -   Core Concepts: user_guide/core_concepts.md
    -   Workflow: user_guide/workflow.md
    -   Best Practices: user_guide/best_practices.md
-   API Reference:
    -   Core: reference/core.md
    -   Tools: reference/tools.md
    -   Models: reference/models.md
-   Examples:
    -   Basic Usage: examples/basic_usage.md
    -   Advanced Usage: examples/advanced_usage.md
-   Contributing:
    -   Development Guide: contributing/development.md
    -   Code Style: contributing/code_style.md
    -   Testing: contributing/testing.md

markdown_extensions:
-   pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
-   pymdownx.inlinehilite
-   pymdownx.snippets
-   pymdownx.superfences
-   attr_list
-   md_in_html
-   admonition
-   codehilite
-   footnotes
-   meta
-   pymdownx.blocks.caption
-   admonition
-   pymdownx.superfences
-   pymdownx.details
-   pymdownx.tabbed
-   pymdownx.highlight
-   pymdownx.emoji
-   pymdownx.tasklist
-   pymdownx.keys
-   pymdownx.snippets
-   pymdownx.magiclink
-   pymdownx.betterem
-   pymdownx.caret
-   pymdownx.tilde
-   pymdownx.mark
-   pymdownx.smartsymbols
-   pymdownx.arithmatex
-   pymdownx.progressbar
-   pymdownx.escapeall

-   toc:
        permalink: true


